---
- name: Install packages on Fedora hosts
  hosts: dnf
  ignore_unreachable: true
  become: yes

  tasks:
    - name: Ensure btop is installed
      dnf:
        name: btop
        state: present

    - name: Ensure RPM Fusion Free repository is enabled
      dnf:
        name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: true

    - name: Ensure RPM Fusion Non-Free repository is enabled
      dnf:
        name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: true

    - name: Ensure VLC multimedia codecs are installed
      dnf:
        name: vlc-plugins-freeworld
        state: present
