---
- name: Config Vim with plugins
  hosts: localhost
  gather_facts: true
  become: false
  vars:
    vim_dir: "{{ ansible_env.HOME }}/.vim"
    vimrc: "{{ ansible_env.HOME }}/.vimrc"

  tasks:
    - name: Install required packages
      package:
        name:
          - vim-enhanced
          - git
          - powerline-fonts
          - fzf
        state: installed
      become: true
      tags:
        - install_packages

    - name: Ensure .vim/{autoload,bundle} directory exists
      file:
        path: "{{ item }}"
        state: directory
        recurse: false
        mode: 0750
      loop:
        - "{{ vim_dir }}"
        - "{{ vim_dir }}/autoload"
        - "{{ vim_dir }}/bundle"

    - name: Ensure Pathogen is in place
      get_url:
        dest: "{{ vim_dir }}/autoload/pathogen.vim"
        url: https://tpo.pe/pathogen.vim

    - name: Deploy plugins
      git:
        dest: "{{ vim_dir }}/bundle/{{ item.name }}"
        repo: "{{ item.url }}"
        clone: true
        update: true
        recursive: false
      loop:
        - name: vim-airline
          url: https://github.com/vim-airline/vim-airline
        - name: nerdtree
          url: https://github.com/preservim/nerdtree
        - name: fzf-vim
          url: https://github.com/junegunn/fzf.vim
        - name: vim-gitgutter
          url: https://github.com/airblade/vim-gitgutter
        - name: vim-fugitive
          url: https://github.com/tpope/vim-fugitive
        - name: vim-floaterm
          url: https://github.com/voldikss/vim-floaterm
        - name: ale
          url: https://github.com/dense-analysis/ale.git
        - name: ctrlp.vim
          url: https://github.com/kien/ctrlp.vim.git

    - name: Ensure .vimrc config in place
      copy:
        src: vimrc
        dest: "{{ vimrc }}"
        backup: true
        mode: 0640
