- name: Config Vim with plugins
  hosts: localhost
  ignore_unreachable: true
  gather_facts: yes
  become: no
  user: javier

  tasks:
    - name: Configure Vim using role
      import_role:
        name: vim
