---
all:
  hosts:
    e14:
      ansible_host: "{{ vault_e14_host }}"
    raspberrypi:
      ansible_host: "{{ vault_rpi_host }}"
    tsunami:
      ansible_host: 192.168.2.14
  vars:
    ansible_user: "{{ vault_user }}"
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    vim_user: "{{ vault_user }}"

home_servers:
  hosts:
    e14: {}
    raspberrypi: {}
    tsunami: {}
  vars:
    local_network: "192.168.2.0/24"
    vpn_networks:
      - "10.8.0.0/24"      # ASUS router OpenVPN
      - "10.59.147.0/24"   # Synology OpenVPN
    allowed_networks: "{{ [local_network] + vpn_networks }}"

dnf:
  hosts:
    e14: {}
    tsunami: {}

fedora_servers:
  hosts:
    tsunami: {}
